
title: JRE's Project Blog
description: A place to talk about my projects
url: https://josepheoff.github.io
theme: minima
show_excerpts: true
markdown: kramdown
mathjax: true
timezone: Europe/Berlin
permalink: /posts/:slug
gems: jekyll-seo-tag
# Google Analytics
google_analytics: UA-150925645-1
plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - README.md
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - .sass-cache
  - CNAME
  - LICENSE
