
title: JRE's Project Blog
description: A place to talk about my projects
url: https://josepheoff.github.io
theme: minima
show_excerpts: true
markdown: kramdown
timezone: Europe/Berlin
permalink: /posts/:slug
gems: - jekyll-seo-tag
exclude:
  - README.md
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - .sass-cache
  - CNAME
  - LICENSE
