title: JRE's Project Blog
description: A place to talk about my projects
url: https://josepheoff.github.io
author: Joseph R. Eoff
logo: "/assets/favicon.png"
theme: minima
show_excerpts: true
markdown: kramdown
mathjax: true
timezone: Europe/Berlin
permalink: /posts/:slug

# Google Analytics
google_analytics: UA-150925645-1
site_logo: "/assets/favicon.png"
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - README.md
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - .sass-cache
  - CNAME
  - LICENSE

disqus:
    shortname: jres-project-blog
